name: Test SMTP Connection

on:
  repository_dispatch:
    types: [test_mail_trigger]

jobs:
  test_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: host47.ssl-net.net
          server_port: 587
          secure: false
          # WICHTIG: Ignoriert Zertifikatsfehler beim STARTTLS Handshake
          ignore_cert: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "BuildHub Connectivity Test"
          to: support@einfachalles.at
          from: support@einfachalles.at
          body: "Connection established for ${{ github.repository }}"
